language: android
dist: trusty
jdk:
  - openjdk14
env:
  global:
    - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
    - BUILD_API=31
    - BUILD_TOOLS=30.0.2
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/cmdline-tools/latest

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - tools
    - android-31
    - build-tools-30.0.2
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O android-commandline-tools-linux.zip
  - mkdir -p ${ANDROID_HOME}/cmdline-tools
  - unzip -q android-commandline-tools-linux.zip -d ${ANDROID_HOME}/cmdline-tools
  - mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
  # - echo "$ANDROID_HOME"
  # - mkdir "$ANDROID_HOME/licenses" || true
  # - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  # - cd ResacaApp
  # - chmod +x gradlew
  # - yes | sdkmanager "platforms;android-31"
  # - yes | sdkmanager "build-tools;30.0.2"
  # - yes | sdkmanager --licenses

before_script:
  # Install Android SDK and run emulator
  - echo 'count=0' > /home/travis/.android/repositories.cfg # avoid harmless sdkmanager warning
  - echo y | ${TOOLS}/bin/sdkmanager "platform-tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "tools" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "build-tools;$BUILD_TOOLS" >/dev/null
  - echo y | ${TOOLS}/bin/sdkmanager "platforms;android-$BUILD_API" >/dev/null

script:
  - cd ResacaApp
  - ./gradlew :app:cleanTestDebugUnitTest :app:testDebugUnitTest --tests "com.sebaslogen.resacaapp.*"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache