name: Unit tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run API Check
        run: ./gradlew apiCheck
        env:
          CI_FLOW: ${{ github.workflow }}

      - name: Run Lint
        run: ./gradlew lint
        env:
          CI_FLOW: ${{ github.workflow }}

      - name: Run tests with code coverage
        run: ./gradlew check
        env:
          CI_FLOW: ${{ github.workflow }}
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
