name: Unit tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Set up our JDK environment
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '16'
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew :sample:cleanTestDebugUnitTest :sample:testDebugUnitTest --tests "com.sebaslogen.resacaapp.*"